import { logger } from "@/lib/logger";

export type AIChatRole = "user" | "assistant";

export interface AIChatMessage {
  role: AIChatRole;
  content: string;
  timestamp?: string;
}

export type AIReportAttachment =
  | {
      kind: "text";
      fileName: string;
      data: string;
    }
  | {
      kind: "image";
      fileName: string;
      mimeType: string;
      data: string; // base64 data
    };

interface AskReportAIParams {
  question: string;
  reportContext: any;
  history: AIChatMessage[];
  attachments?: AIReportAttachment[];
}

const GEMINI_MODEL = "gemini-1.5-flash";

export async function askReportAI(params: AskReportAIParams): Promise<string> {
  const { question, reportContext, history, attachments = [] } = params;

  const apiKey = import.meta.env.VITE_GEN_AI_API_KEY as string | undefined;

  if (!apiKey) {
    logger.error("VITE_GEN_AI_API_KEY is not configured.");
    throw new Error(
      "AI configuration is missing. Please set VITE_GEN_AI_API_KEY in your environment."
    );
  }

  if (!reportContext) {
    throw new Error("No report context available for AI explanation.");
  }

  // Build a compact conversation history
  const historyText =
    history && history.length
      ? history
          .slice(-6) // last few turns are enough
          .map(
            (m) =>
              `${m.role === "user" ? "User" : "Assistant"}: ${m.content.trim()}`
          )
          .join("\n")
      : "No previous conversation.";

  // Prepare attachment descriptions for text files
  const textAttachmentSummaries = attachments
    .filter((a) => a.kind === "text")
    .map((a) => {
      const text = (a as Extract<AIReportAttachment, { kind: "text" }>).data;
      const truncated =
        text.length > 8000 ? text.slice(0, 8000) + "\n...[truncated]..." : text;
      return `File: ${a.fileName}\n${truncated}`;
    })
    .join("\n\n");

  const systemAndContextPrompt = [
    "You are an expert financial and inventory reporting assistant.",
    "You explain reports that are generated by a business inventory system.",
    "Use ONLY the information in the provided JSON report context and any attached file summaries.",
    "Do not invent new numbers that are not present in the context.",
    "When you reference a number, clearly say which field or column it comes from.",
    "If the user asks something that cannot be answered from the context, say that it is not available instead of guessing.",
    "",
    "Report context (JSON):",
    JSON.stringify(reportContext, null, 2),
    "",
    "Conversation so far:",
    historyText,
  ]
    .filter(Boolean)
    .join("\n");

  const textParts: { text: string }[] = [];
  textParts.push({ text: systemAndContextPrompt });

  if (textAttachmentSummaries) {
    textParts.push({
      text:
        "\nAttached file contents (parsed or truncated as needed):\n" +
        textAttachmentSummaries,
    });
  }

  // Build image parts for Gemini vision
  const imageParts =
    attachments
      .filter((a) => a.kind === "image")
      .map((a) => {
        const img = a as Extract<AIReportAttachment, { kind: "image" }>;
        return {
          inlineData: {
            mimeType: img.mimeType,
            data: img.data,
          },
        };
      }) || [];

  // Final user question
  textParts.push({
    text:
      "\nUser question about this report and any attached files:\n" +
      (question || "(no explicit question; provide a helpful explanation)."),
  });

  const contents: any[] = [
    {
      role: "user",
      parts: [...textParts, ...imageParts],
    },
  ];

  try {
    const response = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/${GEMINI_MODEL}:generateContent?key=${encodeURIComponent(
        apiKey
      )}`,
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          contents,
        }),
      }
    );

    if (!response.ok) {
      const errorText = await response.text();
      logger.error("Gemini API error response:", errorText);
      throw new Error(
        `Gemini API error (${response.status}): ${response.statusText}`
      );
    }

    const data = await response.json();
    const candidate = data?.candidates?.[0];
    const parts = candidate?.content?.parts || [];
    const answer =
      parts
        .map((p: any) => (typeof p.text === "string" ? p.text : ""))
        .join("\n")
        .trim() || "I couldn't generate a useful answer for this report.";

    return answer;
  } catch (error: any) {
    logger.error("Error calling Gemini API:", error);
    throw new Error(
      error?.message || "Failed to get a response from the AI service."
    );
  }
}

