import { logger } from "@/lib/logger";

export type AIChatRole = "user" | "assistant";

export interface AIChatMessage {
  role: AIChatRole;
  content: string;
  timestamp?: string;
}

export type AIReportAttachment =
  | {
      kind: "text";
      fileName: string;
      data: string;
    }
  | {
      kind: "image";
      fileName: string;
      mimeType: string;
      data: string; // base64 data
    };

interface AskReportAIParams {
  question: string;
  reportContext: any;
  history: AIChatMessage[];
  attachments?: AIReportAttachment[];
}

// Base model name from env, or a broadly available default.
// Use a concrete model ID (no "-latest" alias) as recommended by the docs.
const RAW_MODEL_ID =
  (import.meta.env.VITE_GEN_AI_MODEL_ID as string | undefined) ||
  "gemini-1.5-flash";

// Normalized resource name used in the URL.
const GEMINI_MODEL = RAW_MODEL_ID.startsWith("models/")
  ? RAW_MODEL_ID
  : `models/${RAW_MODEL_ID}`;

export interface KeyStatusResult {
  ok: boolean;
  message: string;
}

export async function askReportAI(params: AskReportAIParams): Promise<string> {
  const { question, reportContext, history, attachments = [] } = params;

  const apiKey = import.meta.env.VITE_GEN_AI_API_KEY as string | undefined;

  if (!apiKey) {
    logger.error("VITE_GEN_AI_API_KEY is not configured.");
    throw new Error(
      "AI configuration is missing. Please set VITE_GEN_AI_API_KEY in your environment."
    );
  }

  if (!reportContext) {
    throw new Error("No report context available for AI explanation.");
  }

  // Build a compact conversation history
  const historyText =
    history && history.length
      ? history
          .slice(-6) // last few turns are enough
          .map(
            (m) =>
              `${m.role === "user" ? "User" : "Assistant"}: ${m.content.trim()}`
          )
          .join("\n")
      : "No previous conversation.";

  // Prepare attachment descriptions for text files
  const textAttachmentSummaries = attachments
    .filter((a) => a.kind === "text")
    .map((a) => {
      const text = (a as Extract<AIReportAttachment, { kind: "text" }>).data;
      const truncated =
        text.length > 8000 ? text.slice(0, 8000) + "\n...[truncated]..." : text;
      return `File: ${a.fileName}\n${truncated}`;
    })
    .join("\n\n");

  const systemAndContextPrompt = [
    "You are an expert financial and inventory reporting assistant.",
    "You explain reports that are generated by a business inventory system.",
    "Use ONLY the information in the provided JSON report context and any attached file summaries.",
    "Do not invent new numbers that are not present in the context.",
    "When you reference a number, clearly say which field or column it comes from.",
    "If the user asks something that cannot be answered from the context, say that it is not available instead of guessing.",
    "",
    "Apply strict Trading Account logic when you reason about profit and loss:",
    "- Cost of Goods Sold (COGS) = Opening Stock + Net Purchases + Direct Expenses − Closing Stock.",
    "- Net Purchases = Purchases − Purchase Returns, using base amounts that exclude GST/input tax.",
    "- Direct expenses (for example freight inward, loading/unloading, and landing costs that are directly tied to inventory) belong inside COGS, not in indirect/operating expenses.",
    "- Opening Stock is the inventory value at the START of the selected period and must NOT change because of sales or sales returns inside that period.",
    "- Closing Stock is the value of the remaining quantity at the END of the period, valued at consistent cost (for example, a product's purchase_price or another chosen method).",
    "- Sales returns increase stock quantity at ORIGINAL COST (not selling price) and reduce Net Sales; they must not be subtracted directly from COGS or applied to Opening Stock.",
    "- Gross Profit = Net Sales − COGS.",
    "- Net Profit = Gross Profit − Indirect Expenses + Other/Indirect Income.",
    "When the numeric fields in the context do not match these formulas, explicitly point out the mismatch, show the correct calculation using the provided fields, and suggest which component (opening stock, net purchases, direct expenses, closing stock, or net sales) appears inconsistent.",
    "",
    "Report context (JSON):",
    JSON.stringify(reportContext, null, 2),
    "",
    "Conversation so far:",
    historyText,
  ]
    .filter(Boolean)
    .join("\n");

  const textParts: { text: string }[] = [];
  textParts.push({ text: systemAndContextPrompt });

  if (textAttachmentSummaries) {
    textParts.push({
      text:
        "\nAttached file contents (parsed or truncated as needed):\n" +
        textAttachmentSummaries,
    });
  }

  // Build image parts for Gemini vision
  const imageParts =
    attachments
      .filter((a) => a.kind === "image")
      .map((a) => {
        const img = a as Extract<AIReportAttachment, { kind: "image" }>;
        return {
          inlineData: {
            mimeType: img.mimeType,
            data: img.data,
          },
        };
      }) || [];

  // Final user question
  textParts.push({
    text:
      "\nUser question about this report and any attached files:\n" +
      (question || "(no explicit question; provide a helpful explanation)."),
  });

  const contents: any[] = [
    {
      role: "user",
      parts: [...textParts, ...imageParts],
    },
  ];

  try {
    const response = await fetch(
      // Use the v1beta Generative Language endpoint (Gemini API).
      `https://generativelanguage.googleapis.com/v1beta/${GEMINI_MODEL}:generateContent?key=${encodeURIComponent(
        apiKey
      )}`,
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          contents,
        }),
      }
    );

    const text = await response.text();

    if (!response.ok) {
      let apiMessage = text;
      try {
        const parsed = JSON.parse(text);
        apiMessage = parsed?.error?.message || text;
      } catch {
        // ignore JSON parse errors and use raw text
      }

      logger.error("Gemini API error response:", text);
      throw new Error(
        `Gemini API error (${response.status}): ${apiMessage}`
      );
    }

    const data = text ? JSON.parse(text) : {};
    const candidate = data?.candidates?.[0];
    const parts = candidate?.content?.parts || [];
    const answer =
      parts
        .map((p: any) => (typeof p.text === "string" ? p.text : ""))
        .join("\n")
        .trim() || "I couldn't generate a useful answer for this report.";

    return answer;
  } catch (error: any) {
    logger.error("Error calling Gemini API:", error);
    throw new Error(
      error?.message || "Failed to get a response from the AI service."
    );
  }
}

export async function checkGeminiKey(): Promise<KeyStatusResult> {
  const apiKey = import.meta.env.VITE_GEN_AI_API_KEY as string | undefined;

  if (!apiKey) {
    return {
      ok: false,
      message: "VITE_GEN_AI_API_KEY is not configured in the environment.",
    };
  }

  try {
    const response = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models?pageSize=1&key=${encodeURIComponent(
        apiKey
      )}`
    );

    const text = await response.text();

    if (!response.ok) {
      let apiMessage = text;
      try {
        const parsed = JSON.parse(text);
        apiMessage = parsed?.error?.message || text;
      } catch {
        // ignore parse errors
      }

      return {
        ok: false,
        message: `Gemini API error (${response.status}): ${apiMessage}`,
      };
    }

    // Basic sanity check: response should contain a "models" array
    const data = text ? JSON.parse(text) : {};
    const models = data?.models;

    if (Array.isArray(models) && models.length > 0) {
      const firstName = models[0]?.name || "unknown model";
      return {
        ok: true,
        message: `API key is valid. Example model: ${firstName}`,
      };
    }

    return {
      ok: true,
      message: "API key is valid, but no models were returned.",
    };
  } catch (error: any) {
    logger.error("Error checking Gemini API key:", error);
    return {
      ok: false,
      message:
        error?.message ||
        "Failed to contact the Gemini API to verify the key.",
    };
  }
}

