// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { logger } from '@/lib/logger';

const SUPABASE_URL = "https://fxylrxbhcqkwyxhftxxp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ4eWxyeGJoY3Frd3l4aGZ0eHhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0ODg2NTYsImV4cCI6MjA3MDA2NDY1Nn0.ljwBpLMUkzWzSi7RcZIzpxNaGsy5O8bC0mNL2ZXLO_4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Custom storage adapter that works better in production environments
const getStorageAdapter = () => {
  if (typeof window === 'undefined') {
    // Server-side: return a no-op storage
    return {
      getItem: () => null,
      setItem: () => {},
      removeItem: () => {},
    };
  }
  
  // Client-side: use localStorage with error handling
  try {
    return localStorage;
  } catch (error) {
    logger.warn('localStorage not available, using memory storage');
    // Fallback to in-memory storage if localStorage fails
    const memoryStorage: { [key: string]: string } = {};
    return {
      getItem: (key: string) => memoryStorage[key] || null,
      setItem: (key: string, value: string) => { memoryStorage[key] = value; },
      removeItem: (key: string) => { delete memoryStorage[key]; },
    };
  }
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: getStorageAdapter(),
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce', // Use PKCE flow for better security in production
  },
  global: {
    headers: {
      'x-client-info': 'inventory-app',
    },
  },
});